# backend/Dockerfile.lambda
FROM public.ecr.aws/lambda/python:3.10
WORKDIR ${LAMBDA_TASK_ROOT}

COPY backend/app ./app
COPY backend/requirements.runtime.txt ./requirements.txt 

RUN python -m pip install --upgrade pip \
 && pip install -r requirements.txt -t .

CMD ["app/lambda_handler.handler"]
